### ISSUE TITLE
Amazing project! 

### ISSUE THREAD

**Issue by timofonic** [jdryg/dls-schematics#1]
Hello.

I'm an ["Higher Technician in Electronic Maintenance"](
http://www.todofp.es/dctm/todofp/europass/t.superior-loe-ingles/mayo-15/tsmantenimientoelectronicoen.pdf?documentId=0901e72b81d80e17) (click for details) student at a vocational school with ADHD. I repeated the course at a vocational school.

Advenced "dutainment" could ease the learning of adult students, not just children. Some of us have issues having attention to boring stuff, it's a very hard challenge for us :P 

Are you using your own engine for simulation? What about using QUCS? While it's a major overkill, maybe it could be useful for more levels.

The way I see a game about electronics is an adventure game (like monkey Island, etc).

**Comment by jdryg** [comment]
Thanks! Glad you liked it :)

> Are you using your own engine for simulation?

Yes. 

> What about using QUCS? While it's a major overkill, maybe it could be useful for more levels.

I haven't heard of QUCS before but from the [looks of it](http://qucs.sourceforge.net/screenshots.html) it's a lot more generic than what I needed for DLS. DLS is a digital logic simulator. QUCS seems to be a mixed-signal simulator (supports both analog and digital signals).

To be honest, the only reason I started this project is because I wanted to try to build the simulator itself. It wasn't my intention to use an existing simulator to make a game. More like the other way around. Build the simulator, and then figure out how to turn it into a (hopefully) fun game/app. Still searching for ideas on the second part :)

> The way I see a game about electronics is an adventure game (like monkey Island, etc).

[else.HeartBreak()](http://elseheartbreak.com/) is an adventure game about programming, and it looks great. If you mean something like that, unfortunately, this is beyond my skills.

What I have in mind is something closer to [TIS-100](http://www.zachtronics.com/tis-100/) or [Human Resource Machine](http://tomorrowcorporation.com/humanresourcemachine) than else.HeartBreak(). Those two are also beyond my skills, but the basic ideas are more approachable.

Either way, thanks for stopping by.
