### ISSUE TITLE
failed to load  the selected schematic

### ISSUE THREAD

**Issue by letianccc** [jdryg/dls-schematics#28]
[v1.zip](https://github.com/jdryg/dls-schematics/files/9609949/v1.zip)

my schematic file can not load in latest linux version and online version (https://dls.makingartstudios.com/sandbox/).
i have uploaded my schematic file. please help me to load.
thanks.

**Comment by jdryg** [comment]
Latest linux and online versions are 0.16.3.
Your schematic has probably been created with 0.17.x. Schematics created with newer versions are not guaranteed to work with older versions of the app.

Unfortunately I don't have any plans to update either the linux package or the online sandbox at this point.
You can try out Wine in order to run the latest Windows version on linux. I haven't tested it but it should work.

**Comment by letianccc** [comment]
ok, thanks
